package Recipes.SingularityRecipes_Pachinko;

import static gregtech.api.enums.Mods.GregTech;
import static gregtech.api.util.GTModHandler.getModItem;

import java.util.HashMap;
import java.util.Map;

import net.minecraft.item.ItemStack;

public class SingularityPachinkoRecipes_GT_Cable {

    public static final Map<Integer, ItemStack[]> PachinkoRecipes_GT_Cable = new HashMap<>();

    public static void addPachinkoRecipes_GT_Cable() {
        // ULV Tier
        // "1x Red Alloy Wire" - 2000
        PachinkoRecipes_GT_Cable.put(
            2000,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 2000), // "1x Red Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2001), // "2x Red Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2002), // "4x Red Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2003), // "8x Red Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2004), // "12x Red Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2005), // "16x Red Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2006), // "1x Red Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2007), // "2x Red Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2008), // "4x Red Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2009), // "8x Red Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2010), // "12x Red Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2011) // "16x Red Alloy Cable"
            });

        // LV Tier
        // "1x Redstone Alloy Wire" - 30645
        PachinkoRecipes_GT_Cable.put(
            30645,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 1200), // "1x Cobalt Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1201), // "2x Cobalt Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1202), // "4x Cobalt Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1203), // "8x Cobalt Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1204), // "12x Cobalt Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1205), // "16x Cobalt Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1206), // "1x Cobalt Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1207), // "2x Cobalt Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1208), // "4x Cobalt Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1209), // "8x Cobalt Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1210), // "12x Cobalt Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1211), // "16x Cobalt Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1220), // "1x Lead Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1221), // "2x Lead Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1222), // "4x Lead Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1223), // "8x Lead Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1224), // "12x Lead Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1225), // "16x Lead Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1226), // "1x Lead Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1227), // "2x Lead Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1228), // "4x Lead Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1229), // "8x Lead Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1230), // "12x Lead Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1231), // "16x Lead Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1240), // "1x Tin Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1241), // "2x Tin Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1242), // "4x Tin Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1243), // "8x Tin Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1244), // "12x Tin Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1245), // "16x Tin Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1246), // "1x Tin Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1247), // "2x Tin Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1248), // "4x Tin Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1249), // "8x Tin Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1250), // "12x Tin Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1251), // "16x Tin Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1260), // "1x Zinc Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1261), // "2x Zinc Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1262), // "4x Zinc Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1263), // "8x Zinc Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1264), // "12x Zinc Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1265), // "16x Zinc Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1266), // "1x Zinc Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1267), // "2x Zinc Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1268), // "4x Zinc Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1269), // "8x Zinc Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1270), // "12x Zinc Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1271), // "16x Zinc Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1280), // "1x Soldering Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1281), // "2x Soldering Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1282), // "4x Soldering Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1283), // "8x Soldering Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1284), // "12x Soldering Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1285), // "16x Soldering Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1286), // "1x Soldering Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1287), // "2x Soldering Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1288), // "4x Soldering Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1289), // "8x Soldering Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1290), // "12x Soldering Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1291), // "16x Soldering Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30645), // "1x Redstone Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30646), // "2x Redstone Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30647), // "4x Redstone Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30648), // "8x Redstone Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30649), // "12x Redstone Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30650), // "16x Redstone Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30651), // "1x Redstone Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30652), // "2x Redstone Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30653), // "4x Redstone Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30654), // "8x Redstone Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30655), // "12x Redstone Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30656) // "16x Redstone Alloy Cable"
            });

        // MV Tier
        // "1x Superconductor MV Wire" - 2320
        PachinkoRecipes_GT_Cable.put(
            2320,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 1300), // "1x Iron Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1301), // "2x Iron Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1302), // "4x Iron Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1303), // "8x Iron Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1304), // "12x Iron Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1305), // "16x Iron Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1306), // "1x Iron Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1307), // "2x Iron Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1308), // "4x Iron Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1309), // "8x Iron Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1310), // "12x Iron Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1311), // "16x Iron Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1320), // "1x Nickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1321), // "2x Nickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1322), // "4x Nickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1323), // "8x Nickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1324), // "12x Nickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1325), // "16x Nickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1326), // "1x Nickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1327), // "2x Nickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1328), // "4x Nickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1329), // "8x Nickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1330), // "12x Nickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1331), // "16x Nickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1340), // "1x Cupronickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1341), // "2x Cupronickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1342), // "4x Cupronickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1343), // "8x Cupronickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1344), // "12x Cupronickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1345), // "16x Cupronickel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1346), // "1x Cupronickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1347), // "2x Cupronickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1348), // "4x Cupronickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1349), // "8x Cupronickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1350), // "12x Cupronickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1351), // "16x Cupronickel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1360), // "1x Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1361), // "2x Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1362), // "4x Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1363), // "8x Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1364), // "12x Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1365), // "16x Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1366), // "1x Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1367), // "2x Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1368), // "4x Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1369), // "8x Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1370), // "12x Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1371), // "16x Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1380), // "1x Annealed Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1381), // "2x Annealed Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1382), // "4x Annealed Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1383), // "8x Annealed Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1384), // "12x Annealed Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1385), // "16x Annealed Copper Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1386), // "1x Annealed Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1387), // "2x Annealed Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1388), // "4x Annealed Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1389), // "8x Annealed Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1390), // "12x Annealed Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1391), // "16x Annealed Copper Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2200), // "1x Superconductor Base MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2201), // "2x Superconductor Base MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2202), // "4x Superconductor Base MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2203), // "8x Superconductor Base MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2204), // "12x Superconductor Base MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2205), // "16x Superconductor Base MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2320), // "1x Superconductor MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2321), // "2x Superconductor MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2322), // "4x Superconductor MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2323), // "8x Superconductor MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2324), // "12x Superconductor MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2325), // "16x Superconductor MV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11490), // "1x Electrical Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11491), // "2x Electrical Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11492), // "4x Electrical Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11493), // "8x Electrical Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11494), // "12x Electrical Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11495), // "16x Electrical Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11496), // "1x Electrical Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11497), // "2x Electrical Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11498), // "4x Electrical Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11499), // "8x Electrical Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11500), // "12x Electrical Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11501) // "16x Electrical Steel Cable"
            });

        // HV Tier
        // "1x Superconductor HV Wire" - 2340
        PachinkoRecipes_GT_Cable.put(
            2340,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 1400), // "1x Kanthal Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1401), // "2x Kanthal Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1402), // "4x Kanthal Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1403), // "8x Kanthal Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1404), // "12x Kanthal Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1405), // "16x Kanthal Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1406), // "1x Kanthal Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1407), // "2x Kanthal Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1408), // "4x Kanthal Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1409), // "8x Kanthal Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1410), // "12x Kanthal Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1411), // "16x Kanthal Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1420), // "1x Gold Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1421), // "2x Gold Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1422), // "4x Gold Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1423), // "8x Gold Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1424), // "12x Gold Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1425), // "16x Gold Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1426), // "1x Gold Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1427), // "2x Gold Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1428), // "4x Gold Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1429), // "8x Gold Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1430), // "12x Gold Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1431), // "16x Gold Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1440), // "1x Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1441), // "2x Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1442), // "4x Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1443), // "8x Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1444), // "12x Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1445), // "16x Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1446), // "1x Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1447), // "2x Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1448), // "4x Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1449), // "8x Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1450), // "12x Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1451), // "16x Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1460), // "1x Silver Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1461), // "2x Silver Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1462), // "4x Silver Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1463), // "8x Silver Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1464), // "12x Silver Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1465), // "16x Silver Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1466), // "1x Silver Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1467), // "2x Silver Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1468), // "4x Silver Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1469), // "8x Silver Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1470), // "12x Silver Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1471), // "16x Silver Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1480), // "1x Blue Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1481), // "2x Blue Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1482), // "4x Blue Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1483), // "8x Blue Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1484), // "12x Blue Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1485), // "16x Blue Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1486), // "1x Blue Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1487), // "2x Blue Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1488), // "4x Blue Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1489), // "8x Blue Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1490), // "12x Blue Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1491), // "16x Blue Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2220), // "1x Superconductor Base HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2221), // "2x Superconductor Base HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2222), // "4x Superconductor Base HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2223), // "8x Superconductor Base HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2224), // "12x Superconductor Base HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2225), // "16x Superconductor Base HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2340), // "1x Superconductor HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2341), // "2x Superconductor HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2342), // "4x Superconductor HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2343), // "8x Superconductor HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2344), // "12x Superconductor HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2345), // "16x Superconductor HV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11510), // "1x Energetic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11511), // "2x Energetic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11512), // "4x Energetic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11513), // "8x Energetic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11514), // "12x Energetic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11515), // "16x Energetic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11516), // "1x Energetic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11517), // "2x Energetic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11518), // "4x Energetic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11519), // "8x Energetic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11510), // "12x Energetic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11511) // "16x Energetic Alloy Cable"
            });

        // EV Tier
        // "1x Superconductor EV Wire" - 2360
        PachinkoRecipes_GT_Cable.put(
            2360,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 1500), // "1x Nichrome Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1501), // "2x Nichrome Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1502), // "4x Nichrome Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1503), // "8x Nichrome Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1504), // "12x Nichrome Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1505), // "16x Nichrome Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1506), // "1x Nichrome Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1507), // "2x Nichrome Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1508), // "4x Nichrome Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1509), // "8x Nichrome Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1510), // "12x Nichrome Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1511), // "16x Nichrome Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1520), // "1x Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1521), // "2x Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1522), // "4x Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1523), // "8x Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1524), // "12x Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1525), // "16x Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1526), // "1x Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1527), // "2x Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1528), // "4x Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1529), // "8x Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1530), // "12x Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1531), // "16x Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1540), // "1x Black Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1541), // "2x Black Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1542), // "4x Black Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1543), // "8x Black Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1544), // "12x Black Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1545), // "16x Black Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1546), // "1x Black Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1547), // "2x Black Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1548), // "4x Black Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1549), // "8x Black Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1550), // "12x Black Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1551), // "16x Black Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1560), // "1x Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1561), // "2x Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1562), // "4x Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1563), // "8x Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1564), // "12x Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1565), // "16x Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1566), // "1x Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1567), // "2x Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1568), // "4x Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1569), // "8x Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1570), // "12x Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1571), // "16x Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1580), // "1x Aluminium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1581), // "2x Aluminium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1582), // "4x Aluminium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1583), // "8x Aluminium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1584), // "12x Aluminium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1585), // "16x Aluminium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1586), // "1x Aluminium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1587), // "2x Aluminium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1588), // "4x Aluminium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1589), // "8x Aluminium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1590), // "12x Aluminium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1591), // "16x Aluminium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1840), // "1x TPV-Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1841), // "2x TPV-Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1842), // "4x TPV-Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1843), // "8x TPV-Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1844), // "12x TPV-Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1845), // "16x TPV-Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1846), // "1x TPV-Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1847), // "2x TPV-Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1848), // "4x TPV-Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1849), // "8x TPV-Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1850), // "12x TPV-Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1851), // "16x TPV-Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2240), // "1x Superconductor Base EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2241), // "2x Superconductor Base EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2242), // "4x Superconductor Base EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2243), // "8x Superconductor Base EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2244), // "12x Superconductor Base EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2245), // "16x Superconductor Base EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2360), // "1x Superconductor EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2361), // "2x Superconductor EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2362), // "4x Superconductor EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2363), // "8x Superconductor EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2364), // "12x Superconductor EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2365), // "16x Superconductor EV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11530), // "1x Vibrant Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11531), // "2x Vibrant Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11532), // "4x Vibrant Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11533), // "8x Vibrant Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11534), // "12x Vibrant Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11535), // "16x Vibrant Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11536), // "1x Vibrant Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11537), // "2x Vibrant Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11538), // "4x Vibrant Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11539), // "8x Vibrant Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11540), // "12x Vibrant Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11541) // "16x Vibrant Alloy Cable"
            });

        // IV Tier
        // "1x Superconductor IV Wire" - 2380
        PachinkoRecipes_GT_Cable.put(
            2380,
            new ItemStack[] {

                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1600), // "1x Graphene Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1601), // "2x Graphene Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1602), // "4x Graphene Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1603), // "8x Graphene Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1604), // "12x Graphene Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1605), // "16x Graphene Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1640), // "1x Platinum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1641), // "2x Platinum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1642), // "4x Platinum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1643), // "8x Platinum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1644), // "12x Platinum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1645), // "16x Platinum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1646), // "1x Platinum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1647), // "2x Platinum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1648), // "4x Platinum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1649), // "8x Platinum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1650), // "12x Platinum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1651), // "16x Platinum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1660), // "1x Tungstensteel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1661), // "2x Tungstensteel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1662), // "4x Tungstensteel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1663), // "8x Tungstensteel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1664), // "12x Tungstensteel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1665), // "16x Tungstensteel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1666), // "1x Tungstensteel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1667), // "2x Tungstensteel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1668), // "4x Tungstensteel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1669), // "8x Tungstensteel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1670), // "12x Tungstensteel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1671), // "16x Tungstensteel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1680), // "1x Tungsten Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1681), // "2x Tungsten Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1682), // "4x Tungsten Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1683), // "8x Tungsten Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1684), // "12x Tungsten Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1685), // "16x Tungsten Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1686), // "1x Tungsten Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1687), // "2x Tungsten Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1688), // "4x Tungsten Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1689), // "8x Tungsten Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1690), // "12x Tungsten Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1691), // "16x Tungsten Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1860), // "1x End Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1861), // "2x End Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1862), // "4x End Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1863), // "8x End Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1864), // "12x End Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1865), // "16x End Steel Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1866), // "1x End Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1867), // "2x End Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1868), // "4x End Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1869), // "8x End Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1870), // "12x End Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1871), // "16x End Steel Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2260), // "1x Superconductor Base IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2261), // "2x Superconductor Base IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2262), // "4x Superconductor Base IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2263), // "8x Superconductor Base IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2264), // "12x Superconductor Base IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2265), // "16x Superconductor Base IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2380), // "1x Superconductor IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2381), // "2x Superconductor IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2382), // "4x Superconductor IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2383), // "8x Superconductor IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2384), // "12x Superconductor IV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2385) // "16x Superconductor IV Wire"
            });

        // LuV Tier
        // "1x Superconductor LuV Wire" - 2400
        PachinkoRecipes_GT_Cable.put(
            2400,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 1620), // "1x Osmium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1621), // "2x Osmium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1622), // "4x Osmium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1623), // "8x Osmium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1624), // "12x Osmium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1625), // "16x Osmium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1626), // "1x Osmium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1627), // "2x Osmium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1628), // "4x Osmium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1629), // "8x Osmium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1630), // "12x Osmium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1631), // "16x Osmium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1700), // "1x HSS-G Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1701), // "2x HSS-G Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1702), // "4x HSS-G Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1703), // "8x HSS-G Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1704), // "12x HSS-G Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1705), // "16x HSS-G Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1706), // "1x HSS-G Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1707), // "2x HSS-G Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1708), // "4x HSS-G Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1709), // "8x HSS-G Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1710), // "12x HSS-G Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1711), // "16x HSS-G Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1720), // "1x Niobium-Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1721), // "2x Niobium-Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1722), // "4x Niobium-Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1723), // "8x Niobium-Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1724), // "12x Niobium-Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1725), // "16x Niobium-Titanium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1726), // "1x Niobium-Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1727), // "2x Niobium-Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1728), // "4x Niobium-Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1729), // "8x Niobium-Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1730), // "12x Niobium-Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1731), // "16x Niobium-Titanium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1740), // "1x Vanadium-Gallium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1741), // "2x Vanadium-Gallium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1742), // "4x Vanadium-Gallium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1743), // "8x Vanadium-Gallium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1744), // "12x Vanadium-Gallium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1745), // "16x Vanadium-Gallium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1746), // "1x Vanadium-Gallium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1747), // "2x Vanadium-Gallium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1748), // "4x Vanadium-Gallium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1749), // "8x Vanadium-Gallium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1750), // "12x Vanadium-Gallium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1751), // "16x Vanadium-Gallium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1760), // "1x Yttrium Barium Cuprate Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1761), // "2x Yttrium Barium Cuprate Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1762), // "4x Yttrium Barium Cuprate Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1763), // "8x Yttrium Barium Cuprate Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1764), // "12x Yttrium Barium Cuprate Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1765), // "16x Yttrium Barium Cuprate Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1766), // "1x Yttrium Barium Cuprate Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1767), // "2x Yttrium Barium Cuprate Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1768), // "4x Yttrium Barium Cuprate Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1769), // "8x Yttrium Barium Cuprate Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1770), // "12x Yttrium Barium Cuprate Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1771), // "16x Yttrium Barium Cuprate Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2280), // "1x Superconductor Base LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2281), // "2x Superconductor Base LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2282), // "4x Superconductor Base LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2283), // "8x Superconductor Base LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2284), // "12x Superconductor Base LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2285), // "16x Superconductor Base LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2400), // "1x Superconductor LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2401), // "2x Superconductor LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2402), // "4x Superconductor LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2403), // "8x Superconductor LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2404), // "12x Superconductor LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2405), // "16x Superconductor LuV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11550), // "1x Melodic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11551), // "2x Melodic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11552), // "4x Melodic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11553), // "8x Melodic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11554), // "12x Melodic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11555), // "16x Melodic Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11556), // "1x Melodic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11557), // "2x Melodic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11558), // "4x Melodic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11559), // "8x Melodic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11560), // "12x Melodic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11561), // "16x Melodic Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11590), // "1x HSS-E Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11591), // "2x HSS-E Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11592), // "4x HSS-E Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11593), // "8x HSS-E Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11594), // "12x HSS-E Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11595), // "16x HSS-E Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11596), // "1x HSS-E Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11597), // "2x HSS-E Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11598), // "4x HSS-E Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11599), // "8x HSS-E Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11600), // "12x HSS-E Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11601) // "16x HSS-E Cable"
            });

        // ZPM Tier
        // "1x Superconductor ZPM Wire" - 2420
        PachinkoRecipes_GT_Cable.put(
            2420,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 1780), // "1x Naquadah Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1781), // "2x Naquadah Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1782), // "4x Naquadah Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1783), // "8x Naquadah Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1784), // "12x Naquadah Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1785), // "16x Naquadah Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1786), // "1x Naquadah Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1787), // "2x Naquadah Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1788), // "4x Naquadah Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1789), // "8x Naquadah Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1790), // "12x Naquadah Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1791), // "16x Naquadah Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2300), // "1x Superconductor Base ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2301), // "2x Superconductor Base ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2302), // "4x Superconductor Base ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2303), // "8x Superconductor Base ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2304), // "12x Superconductor Base ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2305), // "16x Superconductor Base ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2420), // "1x Superconductor ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2421), // "2x Superconductor ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2422), // "4x Superconductor ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2423), // "8x Superconductor ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2424), // "12x Superconductor ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2425), // "16x Superconductor ZPM Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 10752), // "Plasma Generator Mark IV"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11450), // "1x Trinium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11451), // "2x Trinium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11452), // "4x Trinium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11453), // "8x Trinium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11454), // "12x Trinium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11455), // "16x Trinium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11456), // "1x Trinium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11457), // "2x Trinium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11458), // "4x Trinium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11459), // "8x Trinium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11460), // "12x Trinium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11461), // "16x Trinium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11610), // "1x Osmiridium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11611), // "2x Osmiridium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11612), // "4x Osmiridium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11613), // "8x Osmiridium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11614), // "12x Osmiridium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11615), // "16x Osmiridium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11616), // "1x Osmiridium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11617), // "2x Osmiridium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11618), // "4x Osmiridium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11619), // "8x Osmiridium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11620), // "12x Osmiridium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11621), // "16x Osmiridium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32749), // "1x Signalium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32750), // "2x Signalium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32751), // "4x Signalium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32752), // "8x Signalium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32753), // "12x Signalium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32754), // "16x Signalium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32755), // "1x Signalium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32756), // "2x Signalium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32757), // "4x Signalium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32758), // "8x Signalium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32759), // "12x Signalium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32760) // "16x Signalium Cable"
            });

        // UV Tier
        // "1x Superconductor UV Wire" - 2440
        PachinkoRecipes_GT_Cable.put(
            2440,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 1800), // "1x Naquadah Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1801), // "2x Naquadah Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1802), // "4x Naquadah Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1803), // "8x Naquadah Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1804), // "12x Naquadah Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1805), // "16x Naquadah Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1806), // "1x Naquadah Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1807), // "2x Naquadah Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1808), // "4x Naquadah Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1809), // "8x Naquadah Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1810), // "12x Naquadah Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1811), // "16x Naquadah Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1820), // "1x Duranium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1821), // "2x Duranium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1822), // "4x Duranium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1823), // "8x Duranium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1824), // "12x Duranium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1825), // "16x Duranium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1826), // "1x Duranium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1827), // "2x Duranium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1828), // "4x Duranium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1829), // "8x Duranium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1830), // "12x Duranium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1831), // "16x Duranium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1900), // "1x Fluxed Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1901), // "2x Fluxed Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1902), // "4x Fluxed Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1903), // "8x Fluxed Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1904), // "12x Fluxed Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1905), // "16x Fluxed Electrum Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1906), // "1x Fluxed Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1907), // "2x Fluxed Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1908), // "4x Fluxed Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1909), // "8x Fluxed Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1910), // "12x Fluxed Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 1911), // "16x Fluxed Electrum Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2440), // "1x Superconductor UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2441), // "2x Superconductor UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2442), // "4x Superconductor UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2443), // "8x Superconductor UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2444), // "12x Superconductor UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2445), // "16x Superconductor UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2500), // "1x Superconductor Base UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2501), // "2x Superconductor Base UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2502), // "4x Superconductor Base UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2503), // "8x Superconductor Base UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2504), // "12x Superconductor Base UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2505), // "16x Superconductor Base UV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11570), // "1x Stellar Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11571), // "2x Stellar Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11572), // "4x Stellar Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11573), // "8x Stellar Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11574), // "12x Stellar Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11575), // "16x Stellar Alloy Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11576), // "1x Stellar Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11577), // "2x Stellar Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11578), // "4x Stellar Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11579), // "8x Stellar Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11580), // "12x Stellar Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11581), // "16x Stellar Alloy Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32737), // "1x Lumiium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32738), // "2x Lumiium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32739), // "4x Lumiium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32740), // "8x Lumiium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32741), // "12x Lumiium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32742), // "16x Lumiium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32743), // "1x Lumiium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32744), // "2x Lumiium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32745), // "4x Lumiium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32746), // "8x Lumiium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32747), // "12x Lumiium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 32748) // "16x Lumiium Cable"
            });

        // UHV Tier
        // "1x Superconductor UHV Wire" - 2020
        PachinkoRecipes_GT_Cable.put(
            2020,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 2020), // "1x Superconductor UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2021), // "2x Superconductor UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2022), // "4x Superconductor UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2023), // "8x Superconductor UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2024), // "12x Superconductor UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2025), // "16x Superconductor UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2520), // "1x Superconductor Base UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2521), // "2x Superconductor Base UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2522), // "4x Superconductor Base UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2523), // "8x Superconductor Base UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2524), // "12x Superconductor Base UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2525), // "16x Superconductor Base UHV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2600), // "1x Ichorium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2601), // "2x Ichorium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2602), // "4x Ichorium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2603), // "8x Ichorium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2604), // "12x Ichorium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2605), // "16x Ichorium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11310), // "1x Bedrockium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11311), // "2x Bedrockium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11312), // "4x Bedrockium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11313), // "8x Bedrockium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11314), // "12x Bedrockium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11315), // "16x Bedrockium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11316), // "1x Bedrockium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11317), // "2x Bedrockium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11318), // "4x Bedrockium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11319), // "8x Bedrockium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11320), // "12x Bedrockium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11321), // "16x Bedrockium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11470), // "1x HSS-S Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11471), // "2x HSS-S Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11472), // "4x HSS-S Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11473), // "8x HSS-S Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11474), // "12x HSS-S Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11475), // "16x HSS-S Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11476), // "1x HSS-S Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11477), // "2x HSS-S Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11478), // "4x HSS-S Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11479), // "8x HSS-S Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11480), // "12x HSS-S Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11481) // "16x HSS-S Cable"
            });

        // UEV Tier
        // "1x Superconductor UEV Wire" - 2026
        PachinkoRecipes_GT_Cable.put(
            2026,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 2026), // "1x Superconductor UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2027), // "2x Superconductor UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2028), // "4x Superconductor UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2029), // "8x Superconductor UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2030), // "12x Superconductor UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2031), // "16x Superconductor UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2032), // "1x Superconductor Base UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2033), // "2x Superconductor Base UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2034), // "4x Superconductor Base UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2035), // "8x Superconductor Base UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2036), // "12x Superconductor Base UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2037), // "16x Superconductor Base UEV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11330), // "1x Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11331), // "2x Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11332), // "4x Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11333), // "8x Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11334), // "12x Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11335), // "16x Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11336), // "1x Draconium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11337), // "2x Draconium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11338), // "4x Draconium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11339), // "8x Draconium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11340), // "12x Draconium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11341) // "16x Draconium Cable"
            });

        // UIV Tier
        // "1x Superconductor UIV Wire" - 2081
        PachinkoRecipes_GT_Cable.put(
            2081,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 2052), // "1x Superconductor Base UIV
                                                                                     // Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2053), // "2x Superconductor Base UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2054), // "4x Superconductor Base UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2055), // "8x Superconductor Base UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2056), // "12x Superconductor Base UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2057), // "16x Superconductor Base UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2081), // "1x Superconductor UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2082), // "2x Superconductor UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2083), // "4x Superconductor UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2084), // "8x Superconductor UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2085), // "12x Superconductor UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2086), // "16x Superconductor UIV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11350), // "1x Nether Star Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11351), // "2x Nether Star Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11352), // "4x Nether Star Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11353), // "8x Nether Star Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11354), // "12x Nether Star Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11355), // "16x Nether Star Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11356), // "1x Nether Star Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11357), // "2x Nether Star Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11358), // "4x Nether Star Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11359), // "8x Nether Star Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11360), // "12x Nether Star Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11361), // "16x Nether Star Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30585), // "1x Hypogen Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30586), // "2x Hypogen Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30587), // "4x Hypogen Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30588), // "8x Hypogen Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30589), // "12x Hypogen Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 30590) // "16x Hypogen Wire"
            });

        // UMV Tier
        // "1x Superconductor UMV Wire" - 2089
        PachinkoRecipes_GT_Cable.put(
            2089,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 2072), // "1x Superconductor Base UMV
                                                                                     // Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2073), // "2x Superconductor Base UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2074), // "4x Superconductor Base UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2075), // "8x Superconductor Base UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2076), // "12x Superconductor Base UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2077), // "16x Superconductor Base UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2089), // "1x Superconductor UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2090), // "2x Superconductor UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2091), // "4x Superconductor UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2092), // "8x Superconductor UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2093), // "12x Superconductor UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2094), // "16x Superconductor UMV Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11370), // "1x Quantium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11371), // "2x Quantium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11372), // "4x Quantium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11373), // "8x Quantium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11374), // "12x Quantium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11375), // "16x Quantium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11376), // "1x Quantium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11377), // "2x Quantium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11378), // "4x Quantium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11379), // "8x Quantium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11380), // "12x Quantium Cable"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11381) // "16x Quantium Cable"
            });

        // UXV Tier
        // "1x Black Plutonium Wire" - 11390
        PachinkoRecipes_GT_Cable.put(
            11390,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 11390), // "1x Black Plutonium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11391), // "2x Black Plutonium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11392), // "4x Black Plutonium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11393), // "8x Black Plutonium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11394), // "12x Black Plutonium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11395) // "16x Black Plutonium Wire"
            });

        // MAX Tier
        // "1x SpaceTime Wire" - 2606
        PachinkoRecipes_GT_Cable.put(
            2606,
            new ItemStack[] { getModItem(GregTech.ID, "gt.blockmachines", 1L, 2606), // "1x SpaceTime Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2607), // "2x SpaceTime Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2608), // "4x SpaceTime Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2609), // "8x SpaceTime Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2610), // "12x SpaceTime Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 2611), // "16x SpaceTime Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11410), // "1x Awakened Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11411), // "2x Awakened Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11412), // "4x Awakened Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11413), // "8x Awakened Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11414), // "12x Awakened Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11415), // "16x Awakened Draconium Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11430), // "1x Infinity Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11431), // "2x Infinity Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11432), // "4x Infinity Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11433), // "8x Infinity Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11434), // "12x Infinity Wire"
                getModItem(GregTech.ID, "gt.blockmachines", 1L, 11435) // "16x Infinity Wire"
            });
    }
}
