package EnumList.EnumItemList.EnumMaterialList;

import net.minecraft.item.ItemStack;

import static gregtech.api.enums.Mods.AdvancedSolarPanel;
import static gregtech.api.enums.Mods.GTNHLanthanides;
import static gregtech.api.enums.Mods.GalacticraftAmunRa;
import static gregtech.api.enums.Mods.GalacticraftCore;
import static gregtech.api.enums.Mods.GalacticraftMars;
import static gregtech.api.enums.Mods.GalaxySpace;
import static gregtech.api.enums.Mods.GoodGenerator;
import static gregtech.api.enums.Mods.GregTech;
import static gregtech.api.enums.Mods.IndustrialCraft2;
import static gregtech.api.enums.Mods.KekzTech;
import static gregtech.api.enums.Mods.NewHorizonsCoreMod;
import static gregtech.api.util.GTModHandler.getModItem;

public class MiscPlateList {
    public static final ItemStack Iridium_Iron_Plate = getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1L, 6);
    public static final ItemStack Reinforced_Iridium_Iron_Plate = getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1L, 7);
    public static final ItemStack Irradiant_Reinforced_Iridium_Plate = getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1L, 8);
    public static final ItemStack Lightweight_Plate = getModItem(GalacticraftAmunRa.ID, "item.baseItem", 1L, 15);
    public static final ItemStack Heavy_Duty_Plate_Tier_1 = getModItem(GalacticraftCore.ID, "item.heavyPlating", 1L);
    public static final ItemStack Compressed_Copper_Plate = getModItem(GalacticraftCore.ID, "item.basicItem", 1L, 6);
    public static final ItemStack Compressed_Tin_Plate = getModItem(GalacticraftCore.ID, "item.basicItem", 1L, 7);
    public static final ItemStack Compressed_Aluminium_Plate = getModItem(GalacticraftCore.ID, "item.basicItem", 1L, 8);
    public static final ItemStack Compressed_Steel_Plate = getModItem(GalacticraftCore.ID, "item.basicItem", 1L, 9);
    public static final ItemStack Compressed_Bronze_Plate = getModItem(GalacticraftCore.ID, "item.basicItem", 1L, 10);
    public static final ItemStack Compressed_Iron_Plate = getModItem(GalacticraftCore.ID, "item.basicItem", 1L, 11);
    public static final ItemStack Compressed_Meteoric_Iron_Plate = getModItem(GalacticraftCore.ID, "item.meteoricIronIngot", 1L, 1);
    public static final ItemStack Heavy_Duty_Plate_Tier_3 = getModItem(GalacticraftMars.ID, "item.itemBasicAsteroids", 1L);
    public static final ItemStack Compressed_Titanium_Plate = getModItem(GalacticraftMars.ID, "item.itemBasicAsteroids", 1L, 6);
    public static final ItemStack Heavy_Duty_Plate_Tier_2 = getModItem(GalacticraftMars.ID, "item.null", 1L, 3);
    public static final ItemStack Compressed_Desh_Plate = getModItem(GalacticraftMars.ID, "item.null", 1L, 5);
    public static final ItemStack Compressed_Adamantite = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L);
    public static final ItemStack Compressed_Cobalt = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 1);
    public static final ItemStack Compressed_Duralumin = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 2);
    public static final ItemStack Compressed_Lead = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 3);
    public static final ItemStack Compressed_Magnesium = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 4);
    public static final ItemStack Compressed_Mithril = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 5);
    public static final ItemStack Compressed_Nickel = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 6);
    public static final ItemStack Compressed_Oriharukon = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 7);
    public static final ItemStack Compressed_Platinum = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 8);
    public static final ItemStack Compressed_Tungsten = getModItem(GalaxySpace.ID, "item.CompressedPlates", 1L, 9);
    public static final ItemStack Radiation_Proof_Plate = getModItem(GoodGenerator.ID, "radiationProtectionPlate", 1L);
    public static final ItemStack Advanced_Radiation_Proof_Plate = getModItem(GoodGenerator.ID, "advancedRadiationProtectionPlate", 1L);
    public static final ItemStack Special_Ceramics_Plate = getModItem(GoodGenerator.ID, "specialCeramicsPlate", 1L);
    public static final ItemStack Advanced_Alloy = getModItem(IndustrialCraft2.ID, "itemPartAlloy", 1L);
    public static final ItemStack Carbon_Plate = getModItem(IndustrialCraft2.ID, "itemPartCarbonPlate", 1L);
    public static final ItemStack Iridium_Reinforced_Plate = getModItem(IndustrialCraft2.ID, "itemPartIridium", 1L);
    public static final ItemStack Aluminium_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "AluminiumIronPlate", 1L);
    public static final ItemStack Bio_Carbon_Plate = getModItem(NewHorizonsCoreMod.ID, "BioCarbonPlate", 1L);
    public static final ItemStack Bedrockium_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "BedrockiumIronPlate", 1L);
    public static final ItemStack Compressed_Black_Plutonium_Plate = getModItem(NewHorizonsCoreMod.ID, "BlackPlutoniumCompressedPlate", 1L);
    public static final ItemStack Compressed_Callisto_Ice_Plate = getModItem(NewHorizonsCoreMod.ID, "CallistoIceCompressedPlate", 1L);
    public static final ItemStack Charged_Certus_Quartz_Plate = getModItem(NewHorizonsCoreMod.ID, "ChargedCertusQuartzPlate", 1L);
    public static final ItemStack Compressed_Dual_Copper_Plates = getModItem(NewHorizonsCoreMod.ID, "CopperDualCompressedPlates", 1L);
    public static final ItemStack Chrome_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ChromeIronPlate", 1L);
    public static final ItemStack Compressed_Dual_Desh_Plates = getModItem(NewHorizonsCoreMod.ID, "DeshDualCompressedPlates", 1L);
    public static final ItemStack Heavy_Duty_Plate_Tier_4 = getModItem(NewHorizonsCoreMod.ID, "HeavyDutyPlateTier4", 1L);
    public static final ItemStack Heavy_Duty_Plate_Tier_5 = getModItem(NewHorizonsCoreMod.ID, "HeavyDutyPlateTier5", 1L);
    public static final ItemStack Heavy_Duty_Plate_Tier_6 = getModItem(NewHorizonsCoreMod.ID, "HeavyDutyPlateTier6", 1L);
    public static final ItemStack Heavy_Duty_Plate_Tier_7 = getModItem(NewHorizonsCoreMod.ID, "HeavyDutyPlateTier7", 1L);
    public static final ItemStack Heavy_Duty_Plate_Tier_8 = getModItem(NewHorizonsCoreMod.ID, "HeavyDutyPlateTier8", 1L);
    public static final ItemStack Compressed_Ice_Plate = getModItem(NewHorizonsCoreMod.ID, "IceCompressedPlate", 1L);
    public static final ItemStack Compressed_Dual_Ice_Plates = getModItem(NewHorizonsCoreMod.ID, "IceDualCompressedPlates", 1L);
    public static final ItemStack Irradiant_Reinforced_Aluminium_Plate = getModItem(NewHorizonsCoreMod.ID, "IrradiantReinforcedAluminiumPlate", 1L);
    public static final ItemStack Irradiant_Reinforced_Bedrockium_Plate = getModItem(NewHorizonsCoreMod.ID, "IrradiantReinforcedBedrockiumPlate", 1L);
    public static final ItemStack Irradiant_Reinforced_Chrome_Plate = getModItem(NewHorizonsCoreMod.ID, "IrradiantReinforcedChromePlate", 1L);
    public static final ItemStack Irradiant_Reinforced_Naquadria_Plate = getModItem(NewHorizonsCoreMod.ID, "IrradiantReinforcedNaquadriaPlate", 1L);
    public static final ItemStack Irradiant_Reinforced_Neutronium_Plate = getModItem(NewHorizonsCoreMod.ID, "IrradiantReinforcedNeutroniumPlate", 1L);
    public static final ItemStack Irradiant_Reinforced_Titanium_Plate = getModItem(NewHorizonsCoreMod.ID, "IrradiantReinforcedTitaniumPlate", 1L);
    public static final ItemStack Irradiant_Reinforced_Tungsten_Plate = getModItem(NewHorizonsCoreMod.ID, "IrradiantReinforcedTungstenPlate", 1L);
    public static final ItemStack Irradiant_Reinforced_Tungsten_Steel_Plate = getModItem(NewHorizonsCoreMod.ID, "IrradiantReinforcedTungstenSteelPlate", 1L);
    public static final ItemStack Compressed_Dual_Iron_Plates = getModItem(NewHorizonsCoreMod.ID, "IronDualCompressedPlates", 1L);
    public static final ItemStack Compressed_Lead_Nickel_Plate = getModItem(NewHorizonsCoreMod.ID, "LeadNickelPlate", 1L);
    public static final ItemStack Compressed_Lead_Oriharukon_Plate = getModItem(NewHorizonsCoreMod.ID, "LeadOriharukonPlate", 1L);
    public static final ItemStack Compressed_Ledox_Plate = getModItem(NewHorizonsCoreMod.ID, "LedoxCompressedPlate", 1L);
    public static final ItemStack Compressed_Dual_Meteoric_Iron_Plates = getModItem(NewHorizonsCoreMod.ID, "MeteoricIronDualCompressedPlates", 1L);
    public static final ItemStack Compressed_Mysterious_Crystal_Plate = getModItem(NewHorizonsCoreMod.ID, "MysteriousCrystalCompressedPlate", 1L);
    public static final ItemStack Compressed_Dual_Mysterious_Crystal_Plates = getModItem(NewHorizonsCoreMod.ID, "MysteriousCrystalDualCompressedPlates", 1L);
    public static final ItemStack Compressed_Mytryl_Plate = getModItem(NewHorizonsCoreMod.ID, "MytrylCompressedPlate", 1L);
    public static final ItemStack Compressed_Dual_Mytryl_Plates = getModItem(NewHorizonsCoreMod.ID, "MytrylDualCompressedPlates", 1L);
    public static final ItemStack Nano_Plated_Leggings = getModItem(NewHorizonsCoreMod.ID, "NanoPlatedLeggings", 1L);
    public static final ItemStack Naquadria_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "NaquadriaIronPlate", 1L);
    public static final ItemStack Neutronium_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "NeutroniumIronPlate", 1L);
    public static final ItemStack Compressed_Quantium_Plate = getModItem(NewHorizonsCoreMod.ID, "QuantinumCompressedPlate", 1L);
    public static final ItemStack Compressed_Dual_Quantium_Plates = getModItem(NewHorizonsCoreMod.ID, "QuantinumDualCompressedPlates", 1L);
    public static final ItemStack Reinforced_Glass_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedGlassPlate", 1L);
    public static final ItemStack Reinforced_Aluminium_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedAluminiumIronPlate", 1L);
    public static final ItemStack Reinforced_Bedrockium_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedBedrockiumIronPlate", 1L);
    public static final ItemStack Reinforced_Chrome_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedChromeIronPlate", 1L);
    public static final ItemStack Reinforced_Naquadria_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedNaquadriaIronPlate", 1L);
    public static final ItemStack Reinforced_Neutronium_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedNeutroniumIronPlate", 1L);
    public static final ItemStack Reinforced_Titanium_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedTitaniumIronPlate", 1L);
    public static final ItemStack Reinforced_Tungsten_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedTungstenIronPlate", 1L);
    public static final ItemStack Reinforced_Tungsten_Steel_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "ReinforcedTungstenSteelIronPlate", 1L);
    public static final ItemStack Compressed_Dual_Steel_Plates = getModItem(NewHorizonsCoreMod.ID, "SteelDualCompressedPlates", 1L);
    public static final ItemStack Stone_Plate = getModItem(NewHorizonsCoreMod.ID, "StonePlate", 1L);
    public static final ItemStack Stargate_Radiation_Containment_Plate = getModItem(NewHorizonsCoreMod.ID, "StargateShieldingFoil", 1L);
    public static final ItemStack Compressed_Dual_Tin_Plates = getModItem(NewHorizonsCoreMod.ID, "TinDualCompressedPlates", 1L);
    public static final ItemStack Compressed_Dual_Titanium_Plates = getModItem(NewHorizonsCoreMod.ID, "TitaniumDualCompressedPlates", 1L);
    public static final ItemStack Titanium_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "TitaniumIronPlate", 1L);
    public static final ItemStack Tungsten_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "TungstenIronPlate", 1L);
    public static final ItemStack Tungsten_Steel_Iron_Plate = getModItem(NewHorizonsCoreMod.ID, "TungstenSteelIronPlate", 1L);
    public static final ItemStack Stargate_Plate_of_Split_Origin = getModItem(NewHorizonsCoreMod.ID, "OriginGatePlate", 1L);
    public static final ItemStack Stargate_Plate_of_Polychrome_Contest = getModItem(NewHorizonsCoreMod.ID, "PolychromeGatePlate", 1L);
    public static final ItemStack Stargate_Plate_of_Dimensional_Duplicity = getModItem(NewHorizonsCoreMod.ID, "DimensionalGatePlate", 1L);
    public static final ItemStack Stargate_Plate_of_Harmonic_Breakthrough = getModItem(NewHorizonsCoreMod.ID, "HarmonicGatePlate", 1L);
    public static final ItemStack Beryllium_Shielding_Plate = getModItem(GregTech.ID, "gt.metaitem.03", 1L, 32255);
    public static final ItemStack Iron_Quartz_Plate = getModItem(GTNHLanthanides.ID, "item.iron_quartz_plate", 1L);
    public static final ItemStack YSZ_Ceramic_Plate = getModItem(KekzTech.ID, "kekztech_crafting_item", 1L, 14);
    public static final ItemStack GDC_Ceramic_Plate = getModItem(KekzTech.ID, "kekztech_crafting_item", 1L, 15);

}
