package EnumList.EnumItemList.EnumMiscList;

import net.minecraft.item.ItemStack;

import static gregtech.api.enums.Mods.NewHorizonsCoreMod;
import static gregtech.api.util.GTModHandler.getModItem;

public class CoinList {
    public static final ItemStack Chunkloader_Coin_Tier_I = getModItem(NewHorizonsCoreMod.ID, "CoinChunkloaderTierI", 1L);
    public static final ItemStack Chunkloader_Coin_Tier_II = getModItem(NewHorizonsCoreMod.ID, "CoinChunkloaderTierII", 1L);
    public static final ItemStack Chunkloader_Coin_Tier_III = getModItem(NewHorizonsCoreMod.ID, "CoinChunkloaderTierIII", 1L);
    public static final ItemStack Chunkloader_Coin_Tier_IV = getModItem(NewHorizonsCoreMod.ID, "CoinChunkloaderTierIV", 1L);
    public static final ItemStack Chunkloader_Coin_Tier_V = getModItem(NewHorizonsCoreMod.ID, "CoinChunkloaderTierV", 1L);
    public static final ItemStack Coin_The_Explorer_1 = getModItem(NewHorizonsCoreMod.ID, "CoinAdventure", 1L);
    public static final ItemStack Coin_The_Explorer_10 = getModItem(NewHorizonsCoreMod.ID, "CoinAdventureI", 1L);
    public static final ItemStack Coin_The_Explorer_100 = getModItem(NewHorizonsCoreMod.ID, "CoinAdventureII", 1L);
    public static final ItemStack Coin_The_Explorer_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinAdventureIII", 1L);
    public static final ItemStack Coin_The_Explorer_10k = getModItem(NewHorizonsCoreMod.ID, "CoinAdventureIV", 1L);
    public static final ItemStack Coin_The_Beekeeper_1 = getModItem(NewHorizonsCoreMod.ID, "CoinBees", 1L);
    public static final ItemStack Coin_The_Beekeeper_10 = getModItem(NewHorizonsCoreMod.ID, "CoinBeesI", 1L);
    public static final ItemStack Coin_The_Beekeeper_100 = getModItem(NewHorizonsCoreMod.ID, "CoinBeesII", 1L);
    public static final ItemStack Coin_The_Beekeeper_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinBeesIII", 1L);
    public static final ItemStack Coin_The_Beekeeper_10k = getModItem(NewHorizonsCoreMod.ID, "CoinBeesIV", 1L);
    public static final ItemStack Coin_Blank_1 = getModItem(NewHorizonsCoreMod.ID, "CoinBlank", 1L);
    public static final ItemStack Coin_Blank_10 = getModItem(NewHorizonsCoreMod.ID, "CoinBlankI", 1L);
    public static final ItemStack Coin_Blank_100 = getModItem(NewHorizonsCoreMod.ID, "CoinBlankII", 1L);
    public static final ItemStack Coin_Blank_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinBlankIII", 1L);
    public static final ItemStack Coin_Blank_10k = getModItem(NewHorizonsCoreMod.ID, "CoinBlankIV", 1L);
    public static final ItemStack Coin_The_Vampire_1 = getModItem(NewHorizonsCoreMod.ID, "CoinBlood", 1L);
    public static final ItemStack Coin_The_Vampire_10 = getModItem(NewHorizonsCoreMod.ID, "CoinBloodI", 1L);
    public static final ItemStack Coin_The_Vampire_100 = getModItem(NewHorizonsCoreMod.ID, "CoinBloodII", 1L);
    public static final ItemStack Coin_The_Vampire_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinBloodIII", 1L);
    public static final ItemStack Coin_The_Vampire_10k = getModItem(NewHorizonsCoreMod.ID, "CoinBloodIV", 1L);
    public static final ItemStack Coin_The_Chemist_1 = getModItem(NewHorizonsCoreMod.ID, "CoinChemist", 1L);
    public static final ItemStack Coin_The_Chemist_10 = getModItem(NewHorizonsCoreMod.ID, "CoinChemistI", 1L);
    public static final ItemStack Coin_The_Chemist_100 = getModItem(NewHorizonsCoreMod.ID, "CoinChemistII", 1L);
    public static final ItemStack Coin_The_Chemist_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinChemistIII", 1L);
    public static final ItemStack Coin_The_Chemist_10k = getModItem(NewHorizonsCoreMod.ID, "CoinChemistIV", 1L);
    public static final ItemStack Coin_The_Cook_1 = getModItem(NewHorizonsCoreMod.ID, "CoinCook", 1L);
    public static final ItemStack Coin_The_Cook_10 = getModItem(NewHorizonsCoreMod.ID, "CoinCookI", 1L);
    public static final ItemStack Coin_The_Cook_100 = getModItem(NewHorizonsCoreMod.ID, "CoinCookII", 1L);
    public static final ItemStack Coin_The_Cook_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinCookIII", 1L);
    public static final ItemStack Coin_The_Cook_10k = getModItem(NewHorizonsCoreMod.ID, "CoinCookIV", 1L);
    public static final ItemStack Coin_The_Dark_Wizard_1 = getModItem(NewHorizonsCoreMod.ID, "CoinDarkWizard", 1L);
    public static final ItemStack Coin_The_Dark_Wizard_10 = getModItem(NewHorizonsCoreMod.ID, "CoinDarkWizardI", 1L);
    public static final ItemStack Coin_The_Dark_Wizard_100 = getModItem(NewHorizonsCoreMod.ID, "CoinDarkWizardII", 1L);
    public static final ItemStack Coin_The_Dark_Wizard_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinDarkWizardIII", 1L);
    public static final ItemStack Coin_The_Dark_Wizard_10k = getModItem(NewHorizonsCoreMod.ID, "CoinDarkWizardIV", 1L);
    public static final ItemStack Coin_The_Farmer_1 = getModItem(NewHorizonsCoreMod.ID, "CoinFarmer", 1L);
    public static final ItemStack Coin_The_Farmer_10 = getModItem(NewHorizonsCoreMod.ID, "CoinFarmerI", 1L);
    public static final ItemStack Coin_The_Farmer_100 = getModItem(NewHorizonsCoreMod.ID, "CoinFarmerII", 1L);
    public static final ItemStack Coin_The_Farmer_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinFarmerIII", 1L);
    public static final ItemStack Coin_The_Farmer_10k = getModItem(NewHorizonsCoreMod.ID, "CoinFarmerIV", 1L);
    public static final ItemStack Coin_The_Gardener_1 = getModItem(NewHorizonsCoreMod.ID, "CoinFlower", 1L);
    public static final ItemStack Coin_The_Gardener_10 = getModItem(NewHorizonsCoreMod.ID, "CoinFlowerI", 1L);
    public static final ItemStack Coin_The_Gardener_100 = getModItem(NewHorizonsCoreMod.ID, "CoinFlowerII", 1L);
    public static final ItemStack Coin_The_Gardener_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinFlowerIII", 1L);
    public static final ItemStack Coin_The_Gardener_10k = getModItem(NewHorizonsCoreMod.ID, "CoinFlowerIV", 1L);
    public static final ItemStack Coin_The_Forest_Ranger_1 = getModItem(NewHorizonsCoreMod.ID, "CoinForestry", 1L);
    public static final ItemStack Coin_The_Forest_Ranger_10 = getModItem(NewHorizonsCoreMod.ID, "CoinForestryI", 1L);
    public static final ItemStack Coin_The_Forest_Ranger_100 = getModItem(NewHorizonsCoreMod.ID, "CoinForestryII", 1L);
    public static final ItemStack Coin_The_Forest_Ranger_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinForestryIII", 1L);
    public static final ItemStack Coin_The_Forest_Ranger_10k = getModItem(NewHorizonsCoreMod.ID, "CoinForestryIV", 1L);
    public static final ItemStack Coin_Blacksmith_1 = getModItem(NewHorizonsCoreMod.ID, "CoinSmith", 1L);
    public static final ItemStack Coin_Blacksmith_10 = getModItem(NewHorizonsCoreMod.ID, "CoinSmithI", 1L);
    public static final ItemStack Coin_Blacksmith_100 = getModItem(NewHorizonsCoreMod.ID, "CoinSmithII", 1L);
    public static final ItemStack Coin_Blacksmith_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinSmithIII", 1L);
    public static final ItemStack Coin_Blacksmith_10k = getModItem(NewHorizonsCoreMod.ID, "CoinSmithIV", 1L);
    public static final ItemStack Coin_Spirit_1 = getModItem(NewHorizonsCoreMod.ID, "CoinWitch", 1L);
    public static final ItemStack Coin_Spirit_10 = getModItem(NewHorizonsCoreMod.ID, "CoinWitchI", 1L);
    public static final ItemStack Coin_Spirit_100 = getModItem(NewHorizonsCoreMod.ID, "CoinWitchII", 1L);
    public static final ItemStack Coin_Spirit_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinWitchIII", 1L);
    public static final ItemStack Coin_Spirit_10k = getModItem(NewHorizonsCoreMod.ID, "CoinWitchIV", 1L);
    public static final ItemStack Coin_The_Space_Invaders_1 = getModItem(NewHorizonsCoreMod.ID, "CoinSpace", 1L);
    public static final ItemStack Coin_The_Space_Invaders_10 = getModItem(NewHorizonsCoreMod.ID, "CoinSpaceI", 1L);
    public static final ItemStack Coin_The_Space_Invaders_100 = getModItem(NewHorizonsCoreMod.ID, "CoinSpaceII", 1L);
    public static final ItemStack Coin_The_Space_Invaders_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinSpaceIII", 1L);
    public static final ItemStack Coin_The_Space_Invaders_10k = getModItem(NewHorizonsCoreMod.ID, "CoinSpaceIV", 1L);
    public static final ItemStack Coin_The_Survivor_1 = getModItem(NewHorizonsCoreMod.ID, "CoinSurvivor", 1L);
    public static final ItemStack Coin_The_Survivor_10 = getModItem(NewHorizonsCoreMod.ID, "CoinSurvivorI", 1L);
    public static final ItemStack Coin_The_Survivor_100 = getModItem(NewHorizonsCoreMod.ID, "CoinSurvivorII", 1L);
    public static final ItemStack Coin_The_Survivor_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinSurvivorIII", 1L);
    public static final ItemStack Coin_The_Survivor_10k = getModItem(NewHorizonsCoreMod.ID, "CoinSurvivorIV", 1L);
    public static final ItemStack Coin_The_Technician_1 = getModItem(NewHorizonsCoreMod.ID, "CoinTechnician", 1L);
    public static final ItemStack Coin_The_Technician_10 = getModItem(NewHorizonsCoreMod.ID, "CoinTechnicianI", 1L);
    public static final ItemStack Coin_The_Technician_100 = getModItem(NewHorizonsCoreMod.ID, "CoinTechnicianII", 1L);
    public static final ItemStack Coin_The_Technician_1000 = getModItem(NewHorizonsCoreMod.ID, "CoinTechnicianIII", 1L);
    public static final ItemStack Coin_The_Technician_10k = getModItem(NewHorizonsCoreMod.ID, "CoinTechnicianIV", 1L);

}
