package EnumList.EnumItemList.EnumMiscList;

import net.minecraft.item.ItemStack;

import static gregtech.api.enums.Mods.Avaritia;
import static gregtech.api.enums.Mods.EternalSingularity;
import static gregtech.api.enums.Mods.UniversalSingularities;
import static gregtech.api.util.GTModHandler.getModItem;

public class SingularityList {
    public static final ItemStack Iron_Singularity = getModItem(Avaritia.ID, "Singularity", 1L);
    public static final ItemStack Golden_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 1);
    public static final ItemStack Lapis_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 2);
    public static final ItemStack Redstone_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 3);
    public static final ItemStack Nether_Quartz_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 4);
    public static final ItemStack Copper_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 5);
    public static final ItemStack Tin_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 6);
    public static final ItemStack Leaden_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 7);
    public static final ItemStack Silver_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 8);
    public static final ItemStack Nickel_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 9);
    public static final ItemStack Enderium_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 10);
    public static final ItemStack Clay_Singularity = getModItem(Avaritia.ID, "Singularity", 1L, 11);
    public static final ItemStack Eternal_Singularity = getModItem(EternalSingularity.ID, "eternal_singularity", 1L);
    public static final ItemStack Nitronic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L);
    public static final ItemStack Psychotic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 1);
    public static final ItemStack Spaghettic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 2);
    public static final ItemStack Pneumatic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 3);
    public static final ItemStack Cryptic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 4);
    public static final ItemStack Historic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 5);
    public static final ItemStack Meteoric_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 6);
    public static final ItemStack Gastronomic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 7);
    public static final ItemStack Chromatic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 8);
    public static final ItemStack Prismatic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 9);
    public static final ItemStack Arithmetic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 10);
    public static final ItemStack Galactic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 11);
    public static final ItemStack Hydrolic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 12);
    public static final ItemStack Geologic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 13);
    public static final ItemStack Angelic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 14);
    public static final ItemStack Chronic_Singularity = getModItem(EternalSingularity.ID, "combined_singularity", 1L, 15);
    public static final ItemStack Coal_Singularity = getModItem(UniversalSingularities.ID, "universal.vanilla.singularity", 1L);
    public static final ItemStack Emerald_Singularity = getModItem(UniversalSingularities.ID, "universal.vanilla.singularity", 1L, 1);
    public static final ItemStack Diamond_Singularity = getModItem(UniversalSingularities.ID, "universal.vanilla.singularity", 1L, 2);
    public static final ItemStack Water_Singularity = getModItem(UniversalSingularities.ID, "universal.vanilla.singularity", 1L, 3);
    public static final ItemStack Aluminum_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L);
    public static final ItemStack Brass_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 1);
    public static final ItemStack Bronze_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 2);
    public static final ItemStack Charcoal_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 3);
    public static final ItemStack Electrum_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 4);
    public static final ItemStack Invar_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 5);
    public static final ItemStack Magnesium_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 6);
    public static final ItemStack Osmium_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 7);
    public static final ItemStack Peridot_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 8);
    public static final ItemStack Ruby_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 9);
    public static final ItemStack Sapphire_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 10);
    public static final ItemStack Steel_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 11);
    public static final ItemStack Titanium_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 12);
    public static final ItemStack Tungsten_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 13);
    public static final ItemStack Uranium_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 14);
    public static final ItemStack Zinc_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 15);
    public static final ItemStack Tricalcium_Phosphate_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 16);
    public static final ItemStack Palladium_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 17);
    public static final ItemStack Damascus_Steel_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 18);
    public static final ItemStack Black_Steel_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 19);
    public static final ItemStack Fluxed_Electrum_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 20);
    public static final ItemStack Quicksilver_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 21);
    public static final ItemStack Shadow_Steel_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 22);
    public static final ItemStack Iridium_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 23);
    public static final ItemStack Nether_Star_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 24);
    public static final ItemStack Platinum_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 25);
    public static final ItemStack Naquadria_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 26);
    public static final ItemStack Plutonium_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 27);
    public static final ItemStack Meteoric_Iron_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 28);
    public static final ItemStack Desh_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 29);
    public static final ItemStack Europium_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 30);
    public static final ItemStack Rose_Gold_Singularity = getModItem(UniversalSingularities.ID, "universal.general.singularity", 1L, 32);
    public static final ItemStack Draconium_Singularity = getModItem(UniversalSingularities.ID, "universal.draconicEvolution.singularity", 1L);
    public static final ItemStack Awakened_Draconium_Singularity = getModItem(UniversalSingularities.ID, "universal.draconicEvolution.singularity", 1L, 1);
    public static final ItemStack Conductive_Iron_Singularity = getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1L);
    public static final ItemStack Electrical_Steel_Singularity = getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1L, 1);
    public static final ItemStack Energetic_Alloy_Singularity = getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1L, 2);
    public static final ItemStack Dark_Steel_Singularity = getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1L, 3);
    public static final ItemStack Pulsating_Iron_Singularity = getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1L, 4);
    public static final ItemStack Redstone_Alloy_Singularity = getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1L, 5);
    public static final ItemStack Soularium_Singularity = getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1L, 6);
    public static final ItemStack Vibrant_Alloy_Singularity = getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1L, 7);
    public static final ItemStack Unstable_Ingot_Singularity = getModItem(UniversalSingularities.ID, "universal.extraUtilities.singularity", 1L);
    public static final ItemStack Electrotine_Singularity = getModItem(UniversalSingularities.ID, "universal.projectRed.singularity", 1L);
    public static final ItemStack Obzinite_Singularity = getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1L, 1);
    public static final ItemStack Ardite_Singularity = getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1L, 2);
    public static final ItemStack Cobalt_Singularity = getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1L, 3);
    public static final ItemStack Ender_Singularity = getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1L, 4);
    public static final ItemStack Manyullyn_Singularity = getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1L, 6);
    public static final ItemStack Rubber_Singularity = getModItem(UniversalSingularities.ID, "universal.rubber.singularity", 1L);
    public static final ItemStack Styrene_Butadiene_Rubber_Singularity = getModItem(UniversalSingularities.ID, "universal.rubber.singularity", 1L, 1);
    public static final ItemStack Silicone_Rubber_Singularity = getModItem(UniversalSingularities.ID, "universal.rubber.singularity", 1L, 2);
    public static final ItemStack Polyphenylene_Sulfide_Singularity = getModItem(UniversalSingularities.ID, "universal.rubber.singularity", 1L, 3);
    public static final ItemStack Polyvinyl_Chloride_Singularity = getModItem(UniversalSingularities.ID, "universal.rubber.singularity", 1L, 4);
    public static final ItemStack Elastic_Singularity = getModItem(UniversalSingularities.ID, "universal.rubber.singularity", 1L, 5);
    public static final ItemStack Contaminated_Singularity = getModItem(UniversalSingularities.ID, "universal.toxic.singularity", 1L);
    public static final ItemStack Ultra_Low_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L);
    public static final ItemStack Low_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 1);
    public static final ItemStack Medium_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 2);
    public static final ItemStack High_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 3);
    public static final ItemStack Extreme_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 4);
    public static final ItemStack Insane_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 5);
    public static final ItemStack Ludicrous_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 6);
    public static final ItemStack ZPM_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 7);
    public static final ItemStack Ultimate_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 8);
    public static final ItemStack Highly_Ultimate_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit.singularity", 1L, 9);
    public static final ItemStack Extremely_Ultimate_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit2.singularity", 1L);
    public static final ItemStack Insanely_Ultimate_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit2.singularity", 1L, 1);
    public static final ItemStack Mega_Ultimate_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit2.singularity", 1L, 2);
    public static final ItemStack Extended_Mega_Ultimate_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit2.singularity", 1L, 3);
    public static final ItemStack Maximum_Computation_Singularity = getModItem(UniversalSingularities.ID, "universal.circuit2.singularity", 1L, 4);

}
