package Recipes;

import java.util.HashMap;
import java.util.Map;

import net.minecraft.item.ItemStack;

import gregtech.api.enums.ItemList;

public class SingularityDebugRecipes {

    public static final Map<Integer, Map<Integer, ItemStack>> VoidDebugRecipes = new HashMap<>();

    public static void addVoidDebugRecipes() {
        Map<Integer, ItemStack> ULVRecipes = new HashMap<>();
        ULVRecipes.put(0, ItemList.Casing_ULV.get(1));
        ULVRecipes.put(1, ItemList.Hull_ULV.get(1));
        ULVRecipes.put(2, ItemList.Hatch_Dynamo_ULV.get(1));
        ULVRecipes.put(3, ItemList.Hatch_Energy_ULV.get(1));
        ULVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_ULV.get(1));
        ULVRecipes.put(5, ItemList.Wireless_Hatch_Energy_ULV.get(1));
        ULVRecipes.put(6, ItemList.Hatch_Input_ULV.get(1));
        ULVRecipes.put(7, ItemList.Hatch_Output_ULV.get(1));
        ULVRecipes.put(8, ItemList.Hatch_Input_Bus_ULV.get(1));
        ULVRecipes.put(9, ItemList.Hatch_Output_Bus_ULV.get(1));
        ULVRecipes.put(10, ItemList.NandChip.get(1));

        Map<Integer, ItemStack> LVRecipes = new HashMap<>();
        LVRecipes.put(0, ItemList.Casing_LV.get(1));
        LVRecipes.put(1, ItemList.Hull_LV.get(1));
        LVRecipes.put(2, ItemList.Hatch_Dynamo_LV.get(1));
        LVRecipes.put(3, ItemList.Hatch_Energy_LV.get(1));
        LVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_LV.get(1));
        LVRecipes.put(5, ItemList.Wireless_Hatch_Energy_LV.get(1));
        LVRecipes.put(6, ItemList.Hatch_Input_LV.get(1));
        LVRecipes.put(7, ItemList.Hatch_Output_LV.get(1));
        LVRecipes.put(8, ItemList.Hatch_Input_Bus_LV.get(1));
        LVRecipes.put(9, ItemList.Hatch_Output_Bus_LV.get(1));
        LVRecipes.put(10, ItemList.Electric_Motor_LV.get(1));
        LVRecipes.put(11, ItemList.Electric_Piston_LV.get(1));
        LVRecipes.put(12, ItemList.Electric_Pump_LV.get(1));
        LVRecipes.put(13, ItemList.Conveyor_Module_LV.get(1));
        LVRecipes.put(14, ItemList.Robot_Arm_LV.get(1));
        LVRecipes.put(15, ItemList.Emitter_LV.get(1));
        LVRecipes.put(16, ItemList.Sensor_LV.get(1));
        LVRecipes.put(17, ItemList.Field_Generator_LV.get(1));
        LVRecipes.put(18, ItemList.FluidRegulator_LV.get(1));
        LVRecipes.put(19, ItemList.Circuit_Microprocessor.get(1));

        Map<Integer, ItemStack> MVRecipes = new HashMap<>();
        MVRecipes.put(0, ItemList.Casing_MV.get(1));
        MVRecipes.put(1, ItemList.Hull_MV.get(1));
        MVRecipes.put(2, ItemList.Hatch_Dynamo_MV.get(1));
        MVRecipes.put(3, ItemList.Hatch_Energy_MV.get(1));
        MVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_MV.get(1));
        MVRecipes.put(5, ItemList.Wireless_Hatch_Energy_MV.get(1));
        MVRecipes.put(6, ItemList.Hatch_Input_MV.get(1));
        MVRecipes.put(7, ItemList.Hatch_Output_MV.get(1));
        MVRecipes.put(8, ItemList.Hatch_Input_Bus_MV.get(1));
        MVRecipes.put(9, ItemList.Hatch_Output_Bus_MV.get(1));
        MVRecipes.put(10, ItemList.Electric_Motor_MV.get(1));
        MVRecipes.put(11, ItemList.Electric_Piston_MV.get(1));
        MVRecipes.put(12, ItemList.Electric_Pump_MV.get(1));
        MVRecipes.put(13, ItemList.Conveyor_Module_MV.get(1));
        MVRecipes.put(14, ItemList.Robot_Arm_MV.get(1));
        MVRecipes.put(15, ItemList.Emitter_MV.get(1));
        MVRecipes.put(16, ItemList.Sensor_MV.get(1));
        MVRecipes.put(17, ItemList.Field_Generator_MV.get(1));
        MVRecipes.put(18, ItemList.FluidRegulator_MV.get(1));
        MVRecipes.put(19, ItemList.Circuit_Processor.get(1));

        Map<Integer, ItemStack> HVRecipes = new HashMap<>();
        HVRecipes.put(0, ItemList.Casing_HV.get(1));
        HVRecipes.put(1, ItemList.Hull_HV.get(1));
        HVRecipes.put(2, ItemList.Hatch_Dynamo_HV.get(1));
        HVRecipes.put(3, ItemList.Hatch_Energy_HV.get(1));
        HVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_HV.get(1));
        HVRecipes.put(5, ItemList.Wireless_Hatch_Energy_HV.get(1));
        HVRecipes.put(6, ItemList.Hatch_Input_HV.get(1));
        HVRecipes.put(7, ItemList.Hatch_Output_HV.get(1));
        HVRecipes.put(8, ItemList.Hatch_Input_Bus_HV.get(1));
        HVRecipes.put(9, ItemList.Hatch_Output_Bus_HV.get(1));
        HVRecipes.put(10, ItemList.Electric_Motor_HV.get(1));
        HVRecipes.put(11, ItemList.Electric_Piston_HV.get(1));
        HVRecipes.put(12, ItemList.Electric_Pump_HV.get(1));
        HVRecipes.put(13, ItemList.Conveyor_Module_HV.get(1));
        HVRecipes.put(14, ItemList.Robot_Arm_HV.get(1));
        HVRecipes.put(15, ItemList.Emitter_HV.get(1));
        HVRecipes.put(16, ItemList.Sensor_HV.get(1));
        HVRecipes.put(17, ItemList.Field_Generator_HV.get(1));
        HVRecipes.put(18, ItemList.FluidRegulator_HV.get(1));
        HVRecipes.put(19, ItemList.Circuit_Nanoprocessor.get(1));

        Map<Integer, ItemStack> EVRecipes = new HashMap<>();
        EVRecipes.put(0, ItemList.Casing_EV.get(1));
        EVRecipes.put(1, ItemList.Hull_EV.get(1));
        EVRecipes.put(2, ItemList.Hatch_Dynamo_EV.get(1));
        EVRecipes.put(3, ItemList.Hatch_Energy_EV.get(1));
        EVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_EV.get(1));
        EVRecipes.put(5, ItemList.Wireless_Hatch_Energy_EV.get(1));
        EVRecipes.put(6, ItemList.Hatch_Input_EV.get(1));
        EVRecipes.put(7, ItemList.Hatch_Output_EV.get(1));
        EVRecipes.put(8, ItemList.Hatch_Input_Bus_EV.get(1));
        EVRecipes.put(9, ItemList.Hatch_Output_Bus_EV.get(1));
        EVRecipes.put(10, ItemList.Electric_Motor_EV.get(1));
        EVRecipes.put(11, ItemList.Electric_Piston_EV.get(1));
        EVRecipes.put(12, ItemList.Electric_Pump_EV.get(1));
        EVRecipes.put(13, ItemList.Conveyor_Module_EV.get(1));
        EVRecipes.put(14, ItemList.Robot_Arm_EV.get(1));
        EVRecipes.put(15, ItemList.Emitter_EV.get(1));
        EVRecipes.put(16, ItemList.Sensor_EV.get(1));
        EVRecipes.put(17, ItemList.Field_Generator_EV.get(1));
        EVRecipes.put(18, ItemList.FluidRegulator_EV.get(1));
        EVRecipes.put(19, ItemList.Circuit_Quantumprocessor.get(1));

        Map<Integer, ItemStack> IVRecipes = new HashMap<>();
        IVRecipes.put(0, ItemList.Casing_IV.get(1));
        IVRecipes.put(1, ItemList.Hull_IV.get(1));
        IVRecipes.put(2, ItemList.Hatch_Dynamo_IV.get(1));
        IVRecipes.put(3, ItemList.Hatch_Energy_IV.get(1));
        IVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_IV.get(1));
        IVRecipes.put(5, ItemList.Wireless_Hatch_Energy_IV.get(1));
        IVRecipes.put(6, ItemList.Hatch_Input_IV.get(1));
        IVRecipes.put(7, ItemList.Hatch_Output_IV.get(1));
        IVRecipes.put(8, ItemList.Hatch_Input_Bus_IV.get(1));
        IVRecipes.put(9, ItemList.Hatch_Output_Bus_IV.get(1));
        IVRecipes.put(10, ItemList.Electric_Motor_IV.get(1));
        IVRecipes.put(11, ItemList.Electric_Piston_IV.get(1));
        IVRecipes.put(12, ItemList.Electric_Pump_IV.get(1));
        IVRecipes.put(13, ItemList.Conveyor_Module_IV.get(1));
        IVRecipes.put(14, ItemList.Robot_Arm_IV.get(1));
        IVRecipes.put(15, ItemList.Emitter_IV.get(1));
        IVRecipes.put(16, ItemList.Sensor_IV.get(1));
        IVRecipes.put(17, ItemList.Field_Generator_IV.get(1));
        IVRecipes.put(18, ItemList.FluidRegulator_IV.get(1));
        IVRecipes.put(19, ItemList.Circuit_Crystalprocessor.get(1));

        Map<Integer, ItemStack> LuVRecipes = new HashMap<>();
        LuVRecipes.put(0, ItemList.Casing_LuV.get(1));
        LuVRecipes.put(1, ItemList.Hull_LuV.get(1));
        LuVRecipes.put(2, ItemList.Hatch_Dynamo_LuV.get(1));
        LuVRecipes.put(3, ItemList.Hatch_Energy_LuV.get(1));
        LuVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_LuV.get(1));
        LuVRecipes.put(5, ItemList.Wireless_Hatch_Energy_LuV.get(1));
        LuVRecipes.put(6, ItemList.Hatch_Input_LuV.get(1));
        LuVRecipes.put(7, ItemList.Hatch_Output_LuV.get(1));
        LuVRecipes.put(8, ItemList.Hatch_Input_Bus_LuV.get(1));
        LuVRecipes.put(9, ItemList.Hatch_Output_Bus_LuV.get(1));
        LuVRecipes.put(10, ItemList.Electric_Motor_LuV.get(1));
        LuVRecipes.put(11, ItemList.Electric_Piston_LuV.get(1));
        LuVRecipes.put(12, ItemList.Electric_Pump_LuV.get(1));
        LuVRecipes.put(13, ItemList.Conveyor_Module_LuV.get(1));
        LuVRecipes.put(14, ItemList.Robot_Arm_LuV.get(1));
        LuVRecipes.put(15, ItemList.Emitter_LuV.get(1));
        LuVRecipes.put(16, ItemList.Sensor_LuV.get(1));
        LuVRecipes.put(17, ItemList.Field_Generator_LuV.get(1));
        LuVRecipes.put(18, ItemList.FluidRegulator_LuV.get(1));
        // LuVRecipes.put(19, ItemList.32092.get(1));

        Map<Integer, ItemStack> ZPMRecipes = new HashMap<>();
        ZPMRecipes.put(0, ItemList.Casing_ZPM.get(1));
        ZPMRecipes.put(1, ItemList.Hull_ZPM.get(1));
        ZPMRecipes.put(2, ItemList.Hatch_Dynamo_ZPM.get(1));
        ZPMRecipes.put(3, ItemList.Hatch_Energy_ZPM.get(1));
        ZPMRecipes.put(4, ItemList.Wireless_Dynamo_Energy_ZPM.get(1));
        ZPMRecipes.put(5, ItemList.Wireless_Hatch_Energy_ZPM.get(1));
        ZPMRecipes.put(6, ItemList.Hatch_Input_ZPM.get(1));
        ZPMRecipes.put(7, ItemList.Hatch_Output_ZPM.get(1));
        ZPMRecipes.put(8, ItemList.Hatch_Input_Bus_ZPM.get(1));
        ZPMRecipes.put(9, ItemList.Hatch_Output_Bus_ZPM.get(1));
        ZPMRecipes.put(10, ItemList.Electric_Motor_ZPM.get(1));
        ZPMRecipes.put(11, ItemList.Electric_Piston_ZPM.get(1));
        ZPMRecipes.put(12, ItemList.Electric_Pump_ZPM.get(1));
        ZPMRecipes.put(13, ItemList.Conveyor_Module_ZPM.get(1));
        ZPMRecipes.put(14, ItemList.Robot_Arm_ZPM.get(1));
        ZPMRecipes.put(15, ItemList.Emitter_ZPM.get(1));
        ZPMRecipes.put(16, ItemList.Sensor_ZPM.get(1));
        ZPMRecipes.put(17, ItemList.Field_Generator_ZPM.get(1));
        ZPMRecipes.put(18, ItemList.FluidRegulator_ZPM.get(1));
        ZPMRecipes.put(19, ItemList.Circuit_Bioprocessor.get(1));

        Map<Integer, ItemStack> UVRecipes = new HashMap<>();
        UVRecipes.put(0, ItemList.Casing_UV.get(1));
        UVRecipes.put(1, ItemList.Hull_UV.get(1));
        UVRecipes.put(2, ItemList.Hatch_Dynamo_UV.get(1));
        UVRecipes.put(3, ItemList.Hatch_Energy_UV.get(1));
        UVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_UV.get(1));
        UVRecipes.put(5, ItemList.Wireless_Hatch_Energy_UV.get(1));
        UVRecipes.put(6, ItemList.Hatch_Input_UV.get(1));
        UVRecipes.put(7, ItemList.Hatch_Output_UV.get(1));
        UVRecipes.put(8, ItemList.Hatch_Input_Bus_UV.get(1));
        UVRecipes.put(9, ItemList.Hatch_Output_Bus_UV.get(1));
        UVRecipes.put(10, ItemList.Electric_Motor_UV.get(1));
        UVRecipes.put(11, ItemList.Electric_Piston_UV.get(1));
        UVRecipes.put(12, ItemList.Electric_Pump_UV.get(1));
        UVRecipes.put(13, ItemList.Conveyor_Module_UV.get(1));
        UVRecipes.put(14, ItemList.Robot_Arm_UV.get(1));
        UVRecipes.put(15, ItemList.Emitter_UV.get(1));
        UVRecipes.put(16, ItemList.Sensor_UV.get(1));
        UVRecipes.put(17, ItemList.Field_Generator_UV.get(1));
        UVRecipes.put(18, ItemList.FluidRegulator_UV.get(1));
        UVRecipes.put(19, ItemList.Circuit_OpticalProcessor.get(1));

        Map<Integer, ItemStack> UHVRecipes = new HashMap<>();
        UHVRecipes.put(0, ItemList.Casing_MAX.get(1));
        UHVRecipes.put(1, ItemList.Hull_MAX.get(1));
        UHVRecipes.put(2, ItemList.Hatch_Dynamo_UHV.get(1));
        UHVRecipes.put(3, ItemList.Hatch_Energy_UHV.get(1));
        UHVRecipes.put(4, ItemList.Wireless_Dynamo_Energy_UHV.get(1));
        UHVRecipes.put(5, ItemList.Wireless_Hatch_Energy_UHV.get(1));
        UHVRecipes.put(6, ItemList.Hatch_Input_UHV.get(1));
        UHVRecipes.put(7, ItemList.Hatch_Output_UHV.get(1));
        UHVRecipes.put(8, ItemList.Hatch_Input_Bus_MAX.get(1));
        UHVRecipes.put(9, ItemList.Hatch_Output_Bus_MAX.get(1));
        UHVRecipes.put(10, ItemList.Electric_Motor_UHV.get(1));
        UHVRecipes.put(11, ItemList.Electric_Piston_UHV.get(1));
        UHVRecipes.put(12, ItemList.Electric_Pump_UHV.get(1));
        UHVRecipes.put(13, ItemList.Conveyor_Module_UHV.get(1));
        UHVRecipes.put(14, ItemList.Robot_Arm_UHV.get(1));
        UHVRecipes.put(15, ItemList.Emitter_UHV.get(1));
        UHVRecipes.put(16, ItemList.Sensor_UHV.get(1));
        UHVRecipes.put(17, ItemList.Field_Generator_UHV.get(1));
        UHVRecipes.put(18, ItemList.FluidRegulator_UHV.get(1));
        UHVRecipes.put(19, ItemList.Circuit_ExoticProcessor.get(1));
        UHVRecipes.put(20, ItemList.Circuit_OpticalAssembly.get(1));

        Map<Integer, ItemStack> UEVRecipes = new HashMap<>();
        UEVRecipes.put(0, ItemList.Hull_UEV.get(1));
        UEVRecipes.put(1, ItemList.Hatch_Dynamo_UEV.get(1));
        UEVRecipes.put(2, ItemList.Hatch_Energy_UEV.get(1));
        UEVRecipes.put(3, ItemList.Wireless_Dynamo_Energy_UEV.get(1));
        UEVRecipes.put(4, ItemList.Wireless_Hatch_Energy_UEV.get(1));
        UEVRecipes.put(5, ItemList.Hatch_Input_UEV.get(1));
        UEVRecipes.put(6, ItemList.Hatch_Output_UEV.get(1));
        UEVRecipes.put(7, ItemList.Electric_Motor_UEV.get(1));
        UEVRecipes.put(8, ItemList.Electric_Piston_UEV.get(1));
        UEVRecipes.put(9, ItemList.Electric_Pump_UEV.get(1));
        UEVRecipes.put(10, ItemList.Conveyor_Module_UEV.get(1));
        UEVRecipes.put(11, ItemList.Robot_Arm_UEV.get(1));
        UEVRecipes.put(12, ItemList.Emitter_UEV.get(1));
        UEVRecipes.put(13, ItemList.Sensor_UEV.get(1));
        UEVRecipes.put(14, ItemList.Field_Generator_UEV.get(1));
        UEVRecipes.put(15, ItemList.FluidRegulator_UEV.get(1));
        UEVRecipes.put(16, ItemList.Circuit_CosmicProcessor.get(1));
        UEVRecipes.put(17, ItemList.Circuit_OpticalComputer.get(1));

        Map<Integer, ItemStack> UIVRecipes = new HashMap<>();
        UIVRecipes.put(0, ItemList.Hull_UIV.get(1));
        UIVRecipes.put(1, ItemList.Hatch_Dynamo_UIV.get(1));
        UIVRecipes.put(2, ItemList.Hatch_Energy_UIV.get(1));
        UIVRecipes.put(3, ItemList.Wireless_Dynamo_Energy_UIV.get(1));
        UIVRecipes.put(4, ItemList.Wireless_Hatch_Energy_UIV.get(1));
        UIVRecipes.put(5, ItemList.Hatch_Input_UIV.get(1));
        UIVRecipes.put(6, ItemList.Hatch_Output_UIV.get(1));
        UIVRecipes.put(7, ItemList.Electric_Motor_UIV.get(1));
        UIVRecipes.put(8, ItemList.Electric_Piston_UIV.get(1));
        UIVRecipes.put(9, ItemList.Electric_Pump_UIV.get(1));
        UIVRecipes.put(10, ItemList.Conveyor_Module_UIV.get(1));
        UIVRecipes.put(11, ItemList.Robot_Arm_UIV.get(1));
        UIVRecipes.put(12, ItemList.Emitter_UIV.get(1));
        UIVRecipes.put(13, ItemList.Sensor_UIV.get(1));
        UIVRecipes.put(14, ItemList.Field_Generator_UIV.get(1));
        UIVRecipes.put(15, ItemList.FluidRegulator_UIV.get(1));
        UIVRecipes.put(16, ItemList.Circuit_TranscendentProcessor.get(1));
        UIVRecipes.put(17, ItemList.Circuit_OpticalMainframe.get(1));

        Map<Integer, ItemStack> UMVRecipes = new HashMap<>();
        UMVRecipes.put(0, ItemList.Hull_UMV.get(1));
        UMVRecipes.put(1, ItemList.Hatch_Dynamo_UMV.get(1));
        UMVRecipes.put(2, ItemList.Hatch_Energy_UMV.get(1));
        UMVRecipes.put(3, ItemList.Wireless_Dynamo_Energy_UMV.get(1));
        UMVRecipes.put(4, ItemList.Wireless_Hatch_Energy_UMV.get(1));
        UMVRecipes.put(5, ItemList.Hatch_Input_UMV.get(1));
        UMVRecipes.put(6, ItemList.Hatch_Output_UMV.get(1));
        UMVRecipes.put(7, ItemList.Electric_Motor_UMV.get(1));
        UMVRecipes.put(8, ItemList.Electric_Piston_UMV.get(1));
        UMVRecipes.put(9, ItemList.Electric_Pump_UMV.get(1));
        UMVRecipes.put(10, ItemList.Conveyor_Module_UMV.get(1));
        UMVRecipes.put(11, ItemList.Robot_Arm_UMV.get(1));
        UMVRecipes.put(12, ItemList.Emitter_UMV.get(1));
        UMVRecipes.put(13, ItemList.Sensor_UMV.get(1));
        UMVRecipes.put(14, ItemList.Field_Generator_UMV.get(1));
        UMVRecipes.put(15, ItemList.FluidRegulator_UMV.get(1));

        Map<Integer, ItemStack> UXVRecipes = new HashMap<>();
        UXVRecipes.put(0, ItemList.Hull_UXV.get(1));
        UXVRecipes.put(1, ItemList.Hatch_Dynamo_UXV.get(1));
        UXVRecipes.put(2, ItemList.Hatch_Energy_UXV.get(1));
        UXVRecipes.put(3, ItemList.Wireless_Dynamo_Energy_UXV.get(1));
        UXVRecipes.put(4, ItemList.Wireless_Hatch_Energy_UXV.get(1));
        UXVRecipes.put(5, ItemList.Hatch_Input_UXV.get(1));
        UXVRecipes.put(6, ItemList.Hatch_Output_UXV.get(1));
        UXVRecipes.put(7, ItemList.Electric_Motor_UXV.get(1));
        UXVRecipes.put(8, ItemList.Electric_Piston_UXV.get(1));
        UXVRecipes.put(9, ItemList.Electric_Pump_UXV.get(1));
        UXVRecipes.put(10, ItemList.Conveyor_Module_UXV.get(1));
        UXVRecipes.put(11, ItemList.Robot_Arm_UXV.get(1));
        UXVRecipes.put(12, ItemList.Emitter_UXV.get(1));
        UXVRecipes.put(13, ItemList.Sensor_UXV.get(1));
        UXVRecipes.put(14, ItemList.Field_Generator_UXV.get(1));
        UXVRecipes.put(15, ItemList.FluidRegulator_UXV.get(1));

        VoidDebugRecipes.put(2006, ULVRecipes);
        VoidDebugRecipes.put(30651, LVRecipes);
        VoidDebugRecipes.put(2320, MVRecipes);
        VoidDebugRecipes.put(2340, HVRecipes);
        VoidDebugRecipes.put(2360, EVRecipes);
        VoidDebugRecipes.put(2380, IVRecipes);
        VoidDebugRecipes.put(2400, LuVRecipes);
        VoidDebugRecipes.put(2420, ZPMRecipes);
        VoidDebugRecipes.put(2440, UVRecipes);
        VoidDebugRecipes.put(2020, UHVRecipes);
        VoidDebugRecipes.put(2026, UEVRecipes);
        VoidDebugRecipes.put(2081, UIVRecipes);
        VoidDebugRecipes.put(2089, UMVRecipes);
        VoidDebugRecipes.put(2606, UXVRecipes);
    }
}
